### PR TITLE
add grammy-on-deta-template

### PR DESCRIPTION
**Pull request by waptik**
A repo template on how to deploy a grammY bot on Deta

### CODE REVIEW

**Comment by abdelhai** [comment]
hi @waptik are you sure grammy works on micros? doesn't it need a long-lived connection?

**Comment by waptik** [comment]
> hi @waptik are you sure grammy works on micros? doesn't it need a long-lived connection?

It does work as long as you are using webhooks but the setup is a bit tricky. Also, I noticed the response time is slow on deta.
You can try the demo at [@GrammyOnDetaBot](https://t.me/GrammyOnDetaBot)

**Comment by waptik** [comment]
People have been complaining that they've had issues deploying the template on deta. I haven't had time to thoroughly look into it.

**Comment by abdelhai** [comment]
ok, will add it for now. disabling visor might solve the slow responses issue.

**Pull request closed without merging**
